name: Update Dependency Graph
on:
  push:
    branches:
      - master

concurrency:
  # Only run once for latest commit per ref and cancel other (previous) runs.
  group: dependency-graph-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  dependency-graph:
    name: Update Dependency Graph
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: sbt/setup-sbt@v1
      - uses: scalacenter/sbt-dependency-submission@v3
